// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    local: "http://127.0.0.1:80/"
  }
});

export default function () {
  postman[Request]({
    name: "insert",
    id: "ea6324d9-3e78-4bcd-892d-a3bbe8b4d747",
    method: "POST",
    address: "{{local}}api/users/mongo",
    data: '{\r\n    "FirstName": "melom",\r\n    "LastName": "latest"\r\n}'
  });

  postman[Request]({
    name: "insert log",
    id: "321520d5-6f33-4563-a434-a5931e5d0311",
    method: "POST",
    address: "{{local}}api/logs",
    data:
      '{\r\n    "uid": "manow",\r\n    "history": [\r\n        { "user": "lemon", "bot": "lemon msg"},\r\n        { "user": "melon", "bot": "melon msg"}\r\n    ]\r\n}'
  });
}
